version: '3.8'

services:
  upload-server:
    build: .
    container_name: gerenciamento-upload-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - uploads_data:/uploads
      - ./logs:/app/logs
    environment:
      - UPLOAD_FOLDER=/uploads
      - MAX_FILE_SIZE=10485760  # 10MB
      - ALLOWED_EXTENSIONS=jpg,jpeg
    networks:
      - upload-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx-proxy:
    image: nginx:alpine
    container_name: gerenciamento-nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads_data:/uploads:ro
    depends_on:
      - upload-server
    networks:
      - upload-network

volumes:
  uploads_data:
    driver: local

networks:
  upload-network:
    driver: bridge 